import type { Metadata } from "next";
import { Archivo } from '@next/font/google';
import "./globals.css";

const archivo = Archivo({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo1.svg" sizes="any" />
      </head>
      <body
        className={archivo.className}
      >
        {children}
      </body>
    </html>
  );
}
